version: "2"
linters:
  default: none
  enable:
    - containedctx
    - copyloopvar
    - errcheck
    - ginkgolinter
    - gocritic
    - govet
    - importas      # Enforces consistent import aliases.
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - noctx
    - nilnil
    - testifylint
    - intrange
    - thelper
    - forbidigo

  settings:
    forbidigo:
      analyze-types: true
      forbid:
        - pattern: ^os\.UserHomeDir
          msg: "Do not use os.UserHomeDir(). Use user.HomeDir() instead."
        - pattern: ^context\.Background$
          pkg: ^context$
          msg: "Do not use context.Background() in tests, use t.Context() instead."
        - pattern: ^context\.TODO$
          pkg: ^context$
          msg: "Do not use context.TODO() in tests, use t.Context() instead."
        - pattern: ^os\.MkdirTemp$
          pkg: ^os$
          msg: "Do not use os.MkdirTemp() in tests, use t.TempDir() instead."
        - pattern: ^os\.Setenv$
          pkg: ^os$
          msg: "Do not use os.Setenv() in tests, use t.Setenv() instead."
    gocritic:
      disabled-checks:
        - ifElseChain
        - exitAfterDefer
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    rules:
      # Test-only forbidigo rules should not apply to non-test files
      - path-except: '_test\.go$'
        linters:
          - forbidigo
        text: 'use t\.Context'
      - path-except: '_test\.go$'
        linters:
          - forbidigo
        text: 'use t\.TempDir'
      - path-except: '_test\.go$'
        linters:
          - forbidigo
        text: 'use t\.Setenv'
      - path: cmd/docker-mcp/internal/gateway/dynamic_mcps.go
        linters:
          - gofmt
      - path: cmd/docker-mcp/internal/gateway/dynamic_mcps.go
        linters:
          - gofumpt
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    goimports:
      local-prefixes:
        - github.com/docker/mcp-gateway
