services:
  gateway:
    image: docker/mcp-gateway
    command:
      - --servers=github-official
      - --secrets=docker-desktop:/run/secrets/mcp_secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - mcp_secret

secrets:
  mcp_secret:
    file: .env