services:
  client:
    build: .
    environment:
      - MCP_HOST=http://gateway:9011/mcp
      - MCP_GATEWAY_AUTH_TOKEN=my-secret-token
    depends_on:
      - gateway

  gateway:
    image: docker/mcp-gateway
    command:
      - --transport=streaming
      - --servers=duckduckgo
      - --verbose=false
      - --port=9011
    environment:
      - DOCKER_CONFIG=/etc/docker
      - MCP_GATEWAY_AUTH_TOKEN=my-secret-token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-config.json:/etc/docker/config.json:ro
